/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemakademikitera;

/**
 *
 * @author Alle
 */
public class formasli1 extends javax.swing.JFrame {

    /**
     * Creates new form formasli1
     */
<<<<<<< HEAD
<<<<<<< HEAD
    
    public String idBrg;
    
    public int lok;
    String namaLok;
    String gedung;
            
    Connection conn=null;
    public formasli1(int lok) {
        conn = new KonekDB().getConnection();
        
        String query="SELECT * FROM tempat_peminjaman WHERE id = "+lok;
        Statement stmt;
        try {
            stmt = conn.createStatement();
            
            ResultSet rs = stmt.executeQuery(query);
        
        while(rs.next()){
            this.lok=rs.getInt("id");
            this.namaLok=rs.getString("nama");
            this.gedung=rs.getString("gedung");
        }
        } catch (SQLException ex) {
            Logger.getLogger(formasli1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        tampil_barang();
        
        lokasi.setText(this.namaLok +" gedung "+this.gedung);
=======
    public formasli1() {
        initComponents();
>>>>>>> parent of c3fe62c... Merge branch 'Alya'
=======
    public formasli1() {
        initComponents();
>>>>>>> parent of c3fe62c... Merge branch 'Alya'
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemakademikitera/swing/formkedua.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 370, 630));

        jPanel1.setBackground(new java.awt.Color(239, 160, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
        tablebarang.setMinimumSize(new java.awt.Dimension(33, 0));
        tablebarang.setRowHeight(33);
        tablebarang.setRowMargin(10);
        tablebarang.setSelectionBackground(new java.awt.Color(255, 221, 158));
        jScrollPane1.setViewportView(tablebarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 400, 300));
=======
=======
>>>>>>> parent of c3fe62c... Merge branch 'Alya'
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("ID Barang");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Nama Barang");
        }
<<<<<<< HEAD
>>>>>>> parent of c3fe62c... Merge branch 'Alya'
=======
>>>>>>> parent of c3fe62c... Merge branch 'Alya'

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 410, 330));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 410, -1));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("List Barang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton1.setText("Selesai");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 500, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
<<<<<<< HEAD
        this.idBrg=idbrang.getText();
        if(!idbrang.getText().isEmpty()){
            listbarang barang = new listbarang (this.lok,this.idBrg);
            try {
                if(barang.Pinjam(conn)){
                   kesimpulan kesimpulanw= new kesimpulan();
                   kesimpulanw.setVisible(true);
                   this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(formasli1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_submitMouseClicked
     public ArrayList<listbarang> barang(){
         ArrayList<listbarang> barang1=new ArrayList();
         form formw = new form();                 
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://"+"localhost:3306/sistem_peminjaman", "root","");
            String query="SELECT id, nama FROM barang WHERE jumlah_stok >0 AND id_tempat_pinjam = "+lok;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            listbarang lbar;
            while (rs.next()){
                lbar=new listbarang(Integer.parseInt(rs.getString("Id")), rs.getString("Nama"));
                barang1.add(lbar);
            }
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        return barang1;
    }
     
     public void tampil_barang(){
         ArrayList<listbarang> list =  barang();
         DefaultTableModel model = (DefaultTableModel)tablebarang.getModel();
         Object[] baris = new Object [2];
         for (int i=0;i<list.size(); i++){
             baris[0]=list.get(i).getid();
             baris[1]=list.get(i).getnama();
             model.addRow(baris);
         }
     }
   
=======
    }//GEN-LAST:event_jButton1ActionPerformed

>>>>>>> parent of c3fe62c... Merge branch 'Alya'
=======
    }//GEN-LAST:event_jButton1ActionPerformed

>>>>>>> parent of c3fe62c... Merge branch 'Alya'
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formasli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formasli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formasli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formasli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formasli1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
